[[entry]]
path = "/some/path"
exe = "program.exe"

[[entry]]
type = "StartOne"
path = "/some/path"

[[entry]]
type = "StartOne"
path = "/some/path"
exe = "program.exe"

[[entry]]
type = "StartOne"
path = "/some/path"
exe = "program.exe"
args = []

[[entry]]
type = "StartOne"
path = "/some/path"
exe = "program.exe"
args = "arg"

[[entry]]
type = "StartOne"
path = "/some/path"
exe = "program.exe"
args = ["arg"]

[[entry]]
type = "StartOne"
path = "/some/path"
exe = "program.exe"
args = ["arg1", "arg2"]

[[entry]]
type = "StartMany"
path = "/some/path"
exe = "program.exe"
args = ["argA1", "argB1"]

[[entry]]
type = "StartMany"
path = "/some/path"
exe = "program.exe"
args = [["argA1", "argB1"]]

[[entry]]
type = "StartMany"
path = "/some/path"
exe = "program.exe"
args = [["argA1", "argA2"], ["argB1", "argB2"]]

[[entry]]
type = "StartMany"
path = "/some/path"
exe = "program.exe"
args = [["argA1", "argA2"], ["argB1"], "argC1"]

[[entry]]
type = "Stop"
exe = "program.exe"
